from flask_sqlalchemy import SQLAlchemy
from flask_login import UserMixin
from datetime import datetime

db = SQLAlchemy()

#Models generated by GPT for faster development
class User(UserMixin, db.Model):
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(120), unique=True, nullable=False, index=True)
    name = db.Column(db.String(100), nullable=False)
    password_hash = db.Column(db.String(128))
    created_at = db.Column(db.DateTime, default=datetime.utcnow)
    is_active = db.Column(db.Boolean, default=True)
    
    # Relationship to reviews
    reviews = db.relationship('Review', backref='author', lazy=True, cascade='all, delete-orphan')
    
    def __repr__(self):
        return f'<User {self.email}>'
    
    @property
    def is_illinois_email(self):
        return self.email.endswith('@illinois.edu')
    
class UserRequirements(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), unique=True)
    
    # Core Requirements
    advanced_composition = db.Column(db.Boolean, default=False) # 1
    composition1 = db.Column(db.Boolean, default=False) # 2
    quantitative_reasoning1 = db.Column(db.Boolean, default=False) # 6.1
    quantitative_reasoning2 = db.Column(db.Boolean, default=False) # 6.2
    
    # Cultural Studies
    western_culture = db.Column(db.Boolean, default=False) # 3.1
    non_western_culture = db.Column(db.Boolean, default=False) # 3.2
    us_minority_culture = db.Column(db.Boolean, default=False) # 3.3
    
    # Language Requirement
    language_requirement = db.Column(db.Boolean, default=False)
    
    # General Education Categories
    humanities_arts = db.Column(db.Boolean, default=False) # 4
    social_behavioral = db.Column(db.Boolean, default=False) # 7
    natural_sciences = db.Column(db.Boolean, default=False) # 5
    
    # Subcategories
    humanities_hp = db.Column(db.Boolean, default=False)  # Historical & Philosophical
    humanities_la = db.Column(db.Boolean, default=False)  # Literature & Arts
    social_behavioral_bsc = db.Column(db.Boolean, default=False)  # Behavioral Sciences
    social_behavioral_ss = db.Column(db.Boolean, default=False)   # Social Sciences
    natural_sciences_ls = db.Column(db.Boolean, default=False)    # Life Sciences
    natural_sciences_ps = db.Column(db.Boolean, default=False)    # Physical Sciences
    
    # Additional info
    audit_uploaded = db.Column(db.Boolean, default=False)
    last_updated = db.Column(db.DateTime, default=datetime.utcnow)

    def __repr__(self):
        return f'<UserRequirements for {self.user.email}>'

class Review(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    course_code = db.Column(db.String(20), nullable=False, index=True)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)
    
    # Review content
    rating = db.Column(db.Integer, nullable=False)  # 1-5 stars
    difficulty = db.Column(db.Integer, nullable=False)  # 1-5 difficulty
    workload = db.Column(db.Integer, nullable=False)  # 1-5 workload
    title = db.Column(db.String(200), nullable=False)
    comment = db.Column(db.Text, nullable=False)
    
    # Metadata
    semester_taken = db.Column(db.String(20))  # e.g., "Fall 2024"
    professor = db.Column(db.String(100))
    grade_received = db.Column(db.String(10))  # e.g., "A", "B+", etc.
    
    # Timestamps
    created_at = db.Column(db.DateTime, default=datetime.utcnow)
    updated_at = db.Column(db.DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
    
    # Moderation
    is_flagged = db.Column(db.Boolean, default=False)
    is_approved = db.Column(db.Boolean, default=True)
    
    def __repr__(self):
        return f'<Review {self.course_code} by {self.author.name}>'
    
    @property
    def rating_stars(self):
        return '★' * self.rating + '☆' * (5 - self.rating)
    
    @property
    def difficulty_text(self):
        levels = {1: 'Very Easy', 2: 'Easy', 3: 'Moderate', 4: 'Hard', 5: 'Very Hard'}
        return levels.get(self.difficulty, 'Unknown')
    
    @property
    def workload_text(self):
        levels = {1: 'Very Light', 2: 'Light', 3: 'Moderate', 4: 'Heavy', 5: 'Very Heavy'}
        return levels.get(self.workload, 'Unknown')
    
    @property
    def time_ago(self):
        now = datetime.utcnow()
        diff = now - self.created_at
        
        if diff.days > 365:
            years = diff.days // 365
            return f"{years} year{'s' if years > 1 else ''} ago"
        elif diff.days > 30:
            months = diff.days // 30
            return f"{months} month{'s' if months > 1 else ''} ago"
        elif diff.days > 0:
            return f"{diff.days} day{'s' if diff.days > 1 else ''} ago"
        elif diff.seconds > 3600:
            hours = diff.seconds // 3600
            return f"{hours} hour{'s' if hours > 1 else ''} ago"
        elif diff.seconds > 60:
            minutes = diff.seconds // 60
            return f"{minutes} minute{'s' if minutes > 1 else ''} ago"
        else:
            return "Just now"